Create strings.xml
meizucustoms/android_device_meizu_m1721 pull request #7
Opened 2022-01-09 16:59 UTC by FantomasXX

关于mback反馈的第一个中文版本

2022-01-09 17:00 UTC, tdrkDev commented
@FantomasXX tomas rename commit to m1721: parts: Introduce Chinese language please

2022-01-09 17:02 UTC, rtx4d commented
Looks good to me, after changing name for commit, we can merge this

2022-01-09 17:02 UTC, rtx4d commented
@rtx4d

2022-01-09 17:08 UTC, FantomasXX commented
Thank you for your guidance

2022-01-09 17:19 UTC, FantomasXX commented
m1721: parts: Introduce Chinese language

2022-01-09 17:26 UTC, FantomasXX reviewed
1

2022-01-10 05:38 UTC, urain39 commented on parts/res/values-cn/strings.xml
> + ​        <​item​>酥麻</​item​>
字面翻译更好。

2022-01-10 05:57 UTC, urain39 requested changes

2022-01-10 05:57 UTC, urain39 commented on parts/res/values-cn/strings.xml
> + ​    <​string​ ​name​=​"​custom_seekbar_default_value_to_set​"​>修改默认设置: <​xliff​:​g​ ​id​=​"​v​"​>%s</​xliff​:​g​>\长按检测</​string​>
“\n”不需要翻译，这里是回车符号。后面半句是“长按以设置的意思”。

2022-01-13 14:59 UTC, closed without merging